### ISSUE TITLE
Note about processing `ack` event

### ISSUE THREAD

**Issue by vogdb** [cargomedia/janus-gateway-js#100]
Currently we don't complete transaction on `ack` https://github.com/cargomedia/janus-gateway-js/blob/f4ede2645f4a8c961cfd84f1d31564d456f45ba3/src/transactions.js#L52
Also `ack` events that are coming in response to plugin messages do not reach plugin level processing because they don't contain `handle_id` or `sender` fields. So, if you create a request from plugin and expect an `ack` response, you should expect it on plugin's session.
What shall we do with it? I don't know >_<

**Comment by njam** [comment]
@zazabe might know more?

**Comment by vogdb** [comment]
yes, he definitely knows!

**Comment by zazabe** [comment]
"async" request are always resolved by an event (with the `transaction` key from the request), as explained in the janus documentation:

> The watch , start , pause , switch and stop requests instead are all asynchronous, which means you'll get a notification about their success or failure in an event.

see https://janus.conf.meetecho.com/docs/janus__streaming_8c.html#streamapi 

So [skipping `ack`](https://github.com/cargomedia/janus-gateway-js/blob/master/src/transactions.js#L52) for async request is correct, I don't see anything to change here... let's keep the code as it is!

**Comment by zazabe** [comment]
hum, there's maybe only the `keepalive`... but i think [we don't care about the response](https://github.com/cargomedia/janus-gateway-js/blob/master/src/session.js#L279) in this case...

**Comment by njam** [comment]
Closing for now
