### ISSUE TITLE
Assertion counting problem of chai.js

### ISSUE THREAD

**Issue by vogdb** [cargomedia/janus-gateway-js#21]
chaijs/chai#94

**Comment by vogdb** [comment]
I think we should try https://github.com/sindresorhus/ava

**Comment by vogdb** [comment]
Well. Ava does not have a mechanism of `describe/context` which is very helpful to organize tests sindresorhus/ava#558. I think it's unacceptable tradeoff. At least for me. Will continue to use chai.js + mocha.

**Comment by vogdb** [comment]
The resolution here is to move to AVA as soon as is has 1.0.0 release. Seems to be a silver bullet by that version.

**Comment by vogdb** [comment]
possibly a good choice in the future will be https://github.com/ORESoftware/suman

**Comment by vogdb** [comment]
There are also `testem` and `intern` libraries to look over

**Comment by njam** [comment]
we use karma now
