### ISSUE TITLE
When using in node, no transaction ID is sent to Janus GW.

### ISSUE THREAD

**Issue by petergerten** [cargomedia/janus-gateway-js#61]
I tried the streaming.html example in the browser - and it works as expected.
When I use part of the code in a node.js application, the transaction ID is not sent and Janus GW throws an error (_[(null)] Returning Janus API error 456 (Missing mandatory element (transaction))_
).

browser:
`{"janus":"attach","plugin":"janus.plugin.streaming","transaction":"ej4woril0g","session_id":509630889}`

node.js:
`{"janus":"attach","plugin":"janus.plugin.streaming","session_id":3989553632}`

Code used:

```
var janus = new Janus.Client("ws://127.0.0.1:8188/janus/", {
    keepalive: true
});

janus.createConnection('client')
    .then(function(connection) {
        return connection.createSession();
    })
    .then(function(session) {
        return session.attachPlugin("janus.plugin.streaming");
    })
```

Does anybody know what might cause this?

**Comment by vogdb** [comment]
I have tried:
```js
var Janus = require('janus-gateway-js');

var janus = new Janus.Client(
  "ws://janus-gateway-js.dev.cargomedia.ch:8310/janus",
  {keepalive: true}
);

janus.createConnection('client')
  .then(function(connection) {
    return connection.createSession();
  })
  .then(function(session) {
    return session.attachPlugin("janus.plugin.streaming");
  })
  .then(function(plugin){
    console.log('do we have a plugin? ', !!plugin);
  });
```
output on the latest master:
```
/usr/local/bin/node sample.js
do we have a plugin?  true
```
output on the latest release:
```
/usr/local/bin/node sample.js
do we have a plugin?  false
```

I would recommend to use the latest master if possible. Today or tomorrow we will release a new version that should work.

**Comment by petergerten** [comment]
Thanks for the quick reply. I used master and it indeed solved the problem :)
