### ISSUE TITLE
Add Sauce Labs CI?

### ISSUE THREAD

**Issue by njam** [cargomedia/janus-gateway-js#83]
Could we run the integration tests on Sauce Labs in all supported browsers?

See this example of bootstrap: https://saucelabs.com/u/bootstrap

Could replace https://github.com/cargomedia/janus-gateway-js/pull/71 ?

@vogdb @zazabe wdyt?

**Comment by zazabe** [comment]
I guess it's good to have only one CI that do all, also we need janus somehow to run these integration tests... 
It seems that Travis CI and SauceLabs can work together, Travis would run all unit tests + start all required services (janus docker container?) and then [asks SauceLabs](https://docs.travis-ci.com/user/sauce-connect/) to run [karma integration tests](https://github.com/karma-runner/karma-sauce-launcher) with different browsers. 
Could be great, but I'm not sure it's really working like that :)

**Comment by vogdb** [comment]
Well, we should definitely try it

**Comment by njam** [comment]
Closing due to https://github.com/cargomedia/janus-gateway-js/issues/99
