### ISSUE TITLE
Create integration tests for MediaPlugin and use an EchoTest plugin for testing.

### ISSUE THREAD

**Issue by vogdb** [cargomedia/janus-gateway-js#90]
There is a functionality in MediaPlugin that needs to be tested but for that we need an existing plugin. The simplest plugin should be used. It's EchoTest. The plugins: Audiobridge, audioroom, streaming, rtpbroadcast are too heavy for this purpose.
- test event firing of `media`, `hangup`, `webrtcup`

**Comment by njam** [comment]
Closing all tickets (unmaintained repo)
